//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoTg.Bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TodoTg.Bot.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Cancel.
        /// </summary>
        internal static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Completed.
        /// </summary>
        internal static string CompletedBtn {
            get {
                return ResourceManager.GetString("CompletedBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditBtn {
            get {
                return ResourceManager.GetString("EditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new task title:.
        /// </summary>
        internal static string EnterNewTaskTitle {
            get {
                return ResourceManager.GetString("EnterNewTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a task title:.
        /// </summary>
        internal static string EnterTaskTitle {
            get {
                return ResourceManager.GetString("EnterTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language set to english.
        /// </summary>
        internal static string LangUpdated {
            get {
                return ResourceManager.GetString("LangUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description..
        /// </summary>
        internal static string NoDescription {
            get {
                return ResourceManager.GetString("NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task.
        /// </summary>
        internal static string NoTask {
            get {
                return ResourceManager.GetString("NoTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; has been created..
        /// </summary>
        internal static string TaskCreated {
            get {
                return ResourceManager.GetString("TaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task has been renamed..
        /// </summary>
        internal static string TaskRenamed {
            get {
                return ResourceManager.GetString("TaskRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title is too short. Enter it again:.
        /// </summary>
        internal static string TitleTooShort {
            get {
                return ResourceManager.GetString("TitleTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔲 Uncompleted.
        /// </summary>
        internal static string UncompletedButton {
            get {
                return ResourceManager.GetString("UncompletedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to edit?.
        /// </summary>
        internal static string WhatToEdit {
            get {
                return ResourceManager.GetString("WhatToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your tasks.
        /// </summary>
        internal static string YourTasks {
            get {
                return ResourceManager.GetString("YourTasks", resourceCulture);
            }
        }
    }
}
